x_multiplier: 1.0
x_offset: 0
y_multiplier: 1.0
y_offset: 0
show_vid_window: True
send_mouse_events: True
target_window: DCS
webcam_index: 1
read_file: False
write_file: False
camera_inverted: True

debug: False

# HoughCircles Tunings
#hc_dp: 1
#hc_minDist: 5
#hc_param1: 25
#hc_param2: 25
#hc_minRadius: 2
#hc_maxRadius_divisor: 20.0

# Tuned for binary threshold
# Kinda works
#binary_threshold: True
#hc_dp: 1
#hc_minDist: 5
#hc_param1: 50
#hc_param2: 10
#hc_minRadius: 2
#hc_maxRadius_divisor: 20.0

binary_threshold: True
hc_dp: 1
hc_minDist: 8
hc_param1: 30
hc_param2: 5
hc_minRadius: 3
hc_maxRadius_divisor: 40.0
