
# Adjusts position of mouse relative to what camera sees.
x_multiplier: 1.0
x_offset: 0
y_multiplier: 1.0
y_offset: 0

target_window: DCS
webcam_index: 1
camera_inverted: True

# Debugging / etc settings
show_vid_window: True
send_mouse_events: True
read_file: False
write_file: False
debug: False

# look at previous three frames to determine action
median_frames: 3
mousewheel_activate_frames: 36
mousewheel_turn_frames: 12

# Makes image all-white/all-black to simplify detection
binary_threshold: True
# dot_method can be circles or contours
dot_method: contours

# Contour detector settings
contour_minRadius: 1

# HoughCircle detector settings
hc_dp: 1
hc_minDist: 8
hc_param1: 30
hc_param2: 5
hc_minRadius: 3
hc_maxRadius_divisor: 40.0
