
# Adjusts position of mouse relative to what camera sees.
# multipliers of 0.5 worked ok in VR, for non-vr testing 2.0 worked well.
# offset is decimal percent, ie 0.2 = 20% shift right
x_multiplier: 0.5
x_offset_percent: 0.0
y_multiplier: 0.5
y_offset_percent: 0.0

target_window: DCS
webcam_index: 1
camera_inverted: True

# Debugging / etc settings
show_vid_window: True
send_mouse_events: True
read_file: False
write_file: False
debug: False

# look at previous three frames to determine action
median_frames: 3
mousewheel_activate_frames: 36
mousewheel_turn_frames: 6

# Makes image all-white/all-black to simplify detection
binary_threshold: True
# dot_method can be circles or contours
dot_method: contours

# Contour detector settings
contour_minRadius: 1

# HoughCircle detector settings
hc_dp: 1
hc_minDist: 8
hc_param1: 30
hc_param2: 5
hc_minRadius: 3
hc_maxRadius_divisor: 40.0
